-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 08, 2020 at 12:51 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `BooksWorld`
--

-- --------------------------------------------------------

--
-- Table structure for table `Book`
--

CREATE TABLE `Book` (
  `id` int(11) NOT NULL,
  `name` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `author` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `translator` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `publisher` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photo` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `descr` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rate` double DEFAULT NULL,
  `page_nr` int(11) DEFAULT NULL,
  `link` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `Book`
--

INSERT INTO `Book` (`id`, `name`, `author`, `translator`, `publisher`, `category`, `photo`, `descr`, `rate`, `page_nr`, `link`) VALUES
(1, 'A Man Called Ove', 'Fredrik Backman', NULL, NULL, 'Fiction', 'https://books.google.fr/books/content?id=7mtNAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70Zz4Nou1rFu2kDlRWtFtXg1xQ3o2o9tfZHZAsCjGvVR1x32NjcxxzixMgofz0qRD1OmpoM8vLOB9AKcldDlSEm3_xgARvZGVRJuEmsvEpPPsgF955eaASDBja9ZHv7RQktXeOg', 'Meet Ove. He’s a curmudgeon—the kind of man who points at people he dislikes as if they were burglars caught outside his bedroom window. He has staunch principles, strict routines, and a short fuse. People call him “the bitter neighbor from hell.” But must Ove be bitter just because he doesn’t walk around with a smile plastered to his face all the time?\r\n\r\nBehind the cranky exterior there is a story and a sadness. So when one November morning a chatty young couple with two chatty young daughters move in next door and accidentally flatten Ove’s mailbox, it is the lead-in to a comical and heartwarming tale of unkempt cats, unexpected friendship, and the ancient art of backing up a U-Haul. All of which will change one cranky old man and a local residents’ association to their very foundations.\r\n\r\nA feel-good story in the spirit of The Unlikely Pilgrimage of Harold Fry and Major Pettigrew’s Last Stand, Fredrik Backman’s novel about the angry old man next door is a thoughtful exploration of the profound impact one life has on countless others. “If there was an award for ‘Most Charming Book of the Year,’ this first novel by a Swedish blogger-turned-overnight-sensation would win hands down” (Booklist, starred review).', 4, 352, 'https://books.google.fr/books?id=m7S2CAAAQBAJ&printsec=frontcover&dq=a+man+called+ove&hl=en&sa=X&ved=0ahUKEwjF68OJ4cboAhULxYUKHeP6AWsQ6AEIKDAA#v=onepage&q=a%20man%20called%20ove&f=false'),
(2, 'Little Women', 'Louisa May Alcott', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=9Sjs_5m7vcsC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71Tm6tsZwEwVZu5dgQcVmQ0xLLJcELp0SxlCyx_pauzGyRfskDbV4zSfHX6uAwy8K0SxqwDo6jQqUUxbOKjIXxDERN2GzQfa-w5fnyPYJH5J8sk4nunQxQwp7mU4CXyTNMt7zOo', 'The illustrations for this series were created by Scott McKowen, who, with his wife Christina Poddubiuk, operates Punch & Judy Inc., a company specializing in design and illustration for theater and performing arts. Their projects often involve research into the visual aspects of historical settings and characters. Christina is a theater set and costume designer and contributed advice on the period clothing for the illustrations.\r\n\r\nScott created these drawings in scratchboard an engraving medium which evokes the look of popular art from the period of these stories. Scratchboard is an illustration board with a specifically prepared surface of hard white chalk. A thin layer of black ink is rolled over the surface, and lines are drawn by hand with a sharp knife by scraping through the ink layer to expose the white surface underneath. The finished drawings are then scanned and the color is added digitally.\r\n\r\nThe beautiful Meg, artistic tomboy Jo, doomed Beth, and selfish Amy: since the publication of Little Women in 1869, these four sisters have become America’s most beloved literary siblings. Louisa May Alcott’s rich and realistic portrait has inspired three movies and stirred the emotions of countless young girls. Set in New England during the Civil War, the novel follows the adventures of the March sisters as they struggle to pursue their dreams.', 4.5, 525, 'https://books.google.fr/books?id=9Sjs_5m7vcsC&printsec=frontcover&dq=little+women&hl=en&sa=X&ved=0ahUKEwiitYjKgsjoAhVMzoUKHc1FDHEQ6AEIZDAH#v=onepage&q=little%20women&f=false'),
(3, 'Pride and Prejudice', 'Jane Austen', NULL, NULL, 'Fiction', 'https://books.google.fr/books/content?id=55AFYh5XadkC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70WY8UOXdtudfpm8txpWq9uuFyojzKZnh3ZbmO6hJW7czyUUhWWShWE06OvOeYcCOM7ej1jj1y4g6dcX1SFljENLJ7CaiPa0ANZV48EwSwkZQHnGQKhkuO9duOWsFXQCCArtRxF', 'Elizabeth Bennett is young, clever, and attractive, but she and her four sisters are in dire need of financial security in the shape of husbands. The arrival of the pleasant nice Mr. Bingley and the obscenely arrogant Mr. Darcy in the neighborhood turns all of their lives upside down in this witty drama of friendship, rivalry, enmity, and love. \r\n\r\nJane Austen is arguably the finest female novelist who ever lived and Pride and Prejudice is arguably the finest, and is certainly the most popular, of her novels. An undoubted classic of world literature, its profound Christian morality is all too often missed or wilfully overlooked by today\'s (post)modern critics. Yet Austen saw the follies and foibles of human nature, and the frictions and fidelities of family life, with an incisive eye that penetrates to the very heart of the human condition. This edition of Austen\'s masterpiece includes an introduction by Professor Christopher Blum and several insightful critical essays by leading Austen scholars.', 4, 417, 'https://books.google.fr/books?id=55AFYh5XadkC&printsec=frontcover&dq=Pride+and+Prejudice&hl=en&sa=X&ved=0ahUKEwi7_7eo4cboAhUFqxoKHZWmBfkQ6AEIQTAD#v=onepage&q=Pride%20and%20Prejudice&f=false'),
(4, 'The Girl You Left Behind', 'Jojo Moyes', NULL, NULL, 'Fiction', 'https://books.google.fr/books/content?id=fWR3u6U5kkAC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70-AYHh_JKa1syde-RptDuLOiSWxEzEcQEgqrOoLA_urK44IKsAXXxBWHclCC8qxifLLDYQ1HMb92IEguxKiBmemCYvSiTnwzyec9YEDv823_BFwBnpdkZQI2pajo8gFX1Vp6I4', 'Paris, World War I. Sophie Lefèvre must keep her family safe while her adored husband, Édouard, fights at the front. When their town falls to the Germans, Sophie is forced to serve them every evening at her hotel. From the moment the new Kommandant sets eyes on Sophie’s portrait—painted by her artist husband—a dangerous obsession is born.\r\n \r\nAlmost a century later in London, Sophie’s portrait hangs in the home of Liv Halston, a wedding gift from her young husband before his sudden death. After a chance encounter reveals the portrait’s true worth, a battle begins over its troubled history and Liv’s world is turned upside all over again.', 4, 480, 'https://books.google.fr/books?id=55AFYh5XadkC&printsec=frontcover&dq=Pride+and+Prejudice&hl=en&sa=X&ved=0ahUKEwi7_7eo4cboAhUFqxoKHZWmBfkQ6AEIQTAD#v=onepage&q=Pride%20and%20Prejudice&f=false'),
(5, 'Tuesdays With Morrie', 'Mitch Albom', NULL, NULL, 'Biography & Autobiography', 'https://books.google.fr/books/content?id=ikl91bkuYpMC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73tQioa230CFhqg4neql0GmlUiFrqwnoF1iygMxXSUE50_6wSQtSAfyqLhfVFuHQG1r_v6HjxrVSMI4O-L_5qutQ6sXIClRi8_gDYBmQShZHcnTqVrVH2-z2MtbrqP6KIOQ-sT_', 'Someone older, patient and wise, who understood you when you were young and searching, and gave you sound advice to help you make your way through it?\r\n\r\nFor Mitch Albom, that person was Morrie Schwartz, his college professor from nearly twenty years ago.\r\n\r\nMaybe, like Mitch, you lost track of this mentor as you made your way, and the insights faded. Wouldn\'t you like to see that person again, ask the bigger questions that still haunt you?\r\n\r\nMitch Albom had that second chance. He rediscovered Morrie in the last months of the older man\'s life. Knowing he was dying of ALS - or motor neurone disease - Mitch visited Morrie in his study every Tuesday, just as they used to back in college. Their rekindled relationship turned into one final \'class\': lessons in how to live.\r\n\r\nTUESDAYS WITH MORRIE is a magical chronicle of their time together, through which Mitch shares Morrie\'s lasting gift with the world.\r\n\r\nPraise for Tuesdays with Morrie:\r\n\r\n\'This is a true story that shines and leaves you forever warmed by its afterglow\' Amy Tan\r\n\r\n\'A moving tribute to embracing life\' Glasgow Herald\r\n\r\n\'An extraordinary contribution to the literature of death\' Boston Globe\r\n\r\n\'A beautifully written book of great clarity and wisdom that lovingly captures the simplicity beyond life\'s complexities\' M Scott Peck', 4, 224, 'https://books.google.fr/books?id=ikl91bkuYpMC&printsec=frontcover&dq=tuesdays+with+morrie&hl=en&sa=X&ved=0ahUKEwjN_d7R4cboAhVRrxoKHZWEAgsQ6AEIKDAA#v=onepage&q=tuesdays%20with%20morrie&f=false'),
(6, 'Kafka on the Shore', 'Haruki Murakami', NULL, NULL, 'Fiction', 'https://books.google.fr/books/content?id=L6AtuutQHpwC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70OB7IaByRqsdMhkN62CmRj5klucr6SZ1YtFY2pdqqlMrS_XedxOJD1MFIL4ql4oDjmANvLTRIdDdNmc7gBU2_pUh_oiM1-h8fQFDiG-JQF0ny_vEf1y5wUJrkO290FfSBzs6Zl', 'Kafka Tamura runs away from home at fifteen, under the shadow of his father\'s dark prophesy.\r\n\r\nThe aging Nakata, tracker of lost cats, who never recovered from a bizarre childhood affliction, finds his pleasantly simplified life suddenly turned upside down.\r\n\r\nAs their parallel odysseys unravel, cats converse with people; fish tumble from the sky; a ghost-like pimp deploys a Hegel-spouting girl of the night; a forest harbours soldiers apparently un-aged since World War II. There is a savage killing, but the identity of both victim and killer is a riddle - one of many which combine to create an elegant and dreamlike masterpiece.', 4, 512, 'https://books.google.fr/books?id=L6AtuutQHpwC&printsec=frontcover&dq=kafka+on+the+shore&hl=en&sa=X&ved=0ahUKEwjzs9Tf4cboAhVRx4UKHatzCqYQ6AEIKDAA#v=onepage&q=kafka%20on%20the%20shore&f=false'),
(7, 'Five Feet Apart', 'Rachael Lippincott', NULL, NULL, 'Young Adult Fiction', 'https://books.google.fr/books/content?id=b0ZXDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE737nfUS_s2MDXMpicngbonwwgu7j331BB9FMhJvSXZgHJGW0GpBVqOdGekXkzDGOHeSP4Wt4-H5CVrOhGm7T6P6v9zBTfCM1DG1UvI33ZTd3KaZ1UmkVPuvQktYlSja2ks2LMSe', 'Can you love someone you can never touch?\r\nStella Grant likes to be in control—even though her totally out of control lungs have sent her in and out of the hospital most of her life. At this point, what Stella needs to control most is keeping herself away from anyone or anything that might pass along an infection and jeopardize the possibility of a lung transplant. Six feet apart. No exceptions.\r\nThe only thing Will Newman wants to be in control of is getting out of this hospital. He couldn’t care less about his treatments, or a fancy new clinical drug trial. Soon, he’ll turn eighteen and then he’ll be able to unplug all these machines and actually go see the world, not just its hospitals.\r\nWill’s exactly what Stella needs to stay away from. If he so much as breathes on Stella she could lose her spot on the transplant list. Either one of them could die. The only way to stay alive is to stay apart. But suddenly six feet doesn’t feel like safety. It feels like punishment.\r\nWhat if they could steal back just a little bit of the space their broken lungs have stolen from them? Would five feet apart really be so dangerous if it stops their hearts from breaking too?', 4.5, 288, 'https://books.google.fr/books?id=b0ZXDwAAQBAJ&printsec=frontcover&dq=five+feet+apart&hl=en&sa=X&ved=0ahUKEwifntPr4cboAhWJ4IUKHWWQC9AQ6AEIKDAA#v=onepage&q=five%20feet%20apart&f=false'),
(8, 'The Five People You Meet In Heaven', 'Mitch Albom', NULL, NULL, 'Fiction ', 'https://books.google.fr/books/content?id=-3TLU1yK8V4C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72ahs7m7xLxs5npDMmF2D8-ThKLvoA_siJk-T-4dh2gPw_JW_OV4FFg_D3SyP_WYrvV4M55cGotdIQ0FFnoYby_gA9R1eY20jsFQPq3RG7xfkhBI8O2eY-LSaZDbi8UPxiv7x3d', 'The novel\'s protagonist is an elderly amusement park maintenance worker named Eddie who, while operating a ride called the \'Free Fall\', dies while trying to save a young girl who gets in the way of a falling cart that hurtles to earth. Eddie goes to heaven, where he meets five people who were unexpectedly instrumental in some way in his life. While each guide takes him through heaven, Eddie learns a little bit more about what his time on earth meant, what he was supposed to have learned, and what his true purpose on earth was.\r\n\r\nThroughout there are dramatic flashbacks where we see scenes from his troubled childhood, his years in the army in the Philippines jungle, and with his first and only love, his wife Marguerite', 4.5, 240, 'https://books.google.fr/books?id=-3TLU1yK8V4C&printsec=frontcover&dq=five+people+you+meet+in+heaven&hl=en&sa=X&ved=0ahUKEwj-veT54cboAhUlyYUKHYBtCh8Q6AEIKDAA#v=onepage&q=five%20people%20you%20meet%20in%20heaven&f=false'),
(9, 'The Next Person You Meet in Heaven', 'Mitch Albom', NULL, NULL, 'Fiction ', 'https://books.google.fr/books/content?id=XftNDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71qMQqxvaUoLCI-_e6i7Xo_qlhiRTkka4iwqUQC5WTHk0xKNksKcnV8T0gYAFuEHASidpJCrPU6tb753lQaxOJKFDCGeMc_Sdk45WYwQ1EFRvqjTYa76TUTvatLPxtSKFAP7eNm', 'Fifteen years ago Eddie, an amusement park mechanic, died saving the life of a young girl named Annie. The accident took Annie\'s left hand, which needed to be surgically reattached. Scarred, and unable to remember why, Annie was whisked away from the world she knew by her guilt-ravaged mother. As a young woman Annie reconnects with Paulo, her childhood love, and believes she has finally found happiness. When their wedding night ends in an unimaginable accident, Annie finds herself on her own heavenly journey -- and an inevitable reunion with Eddie, one of the five people who will show her how her life mattered in ways she could not have fathomed.', 5, 213, 'https://books.google.fr/books?id=XftNDwAAQBAJ&printsec=frontcover&dq=next+people+you+meet+in+heaven&hl=en&sa=X&ved=0ahUKEwiKo-qE4sboAhUIrxoKHdHGA8QQ6AEIKDAA#v=onepage&q=next%20people%20you%20meet%20in%20heaven&f=false'),
(10, 'War and Peace', 'Leo Tolstoy', NULL, NULL, 'Fiction ', 'https://books.google.fr/books/content?id=bTDscs8_1sUC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73kbQQLDyF-IW8IbZrczfOKwfJhA8YrkFOtoqrKqDHpBKWuRrNLY4C58z648bJd6dJDdIkVTT_i1A9FWBHReU1Lkb6O_FF7WjLb7fnT1j4lAEuadhBnokaE6TwXvPS3PFndpFGD', '“The greatest of all novelists...what else can we call the author of War and Peace?” asked Virginia Woolf rhetorically—and literary luminaries the world over have agreed with her. The saga stands alone in its vast scope and minute detail, its immense diversity and final unity. Set in the years leading up to and culminating in Napoleon’s disastrous Russian invasion, the novel focuses upon an entire society torn by conflict and change. Here is humanity in all its innocence and corruption, wisdom and folly, painful defeats and enduring triumphs. Here is the seemingly effortless artistry of a master capable of portraying with equal power the clash of armies and the solitary anguish of the heart. Here, finally, is a view of history and personal destiny that is perpetually modern.', 4.5, 1456, 'https://books.google.fr/books?id=bTDscs8_1sUC&printsec=frontcover&dq=war+and+peace&hl=en&sa=X&ved=0ahUKEwjxmpKP4sboAhVIQRoKHbG8BsoQ6AEIOTAC#v=onepage&q=war%20and%20peace&f=false'),
(11, 'Dear Life', 'Alice Munro', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=xueea93b7AwC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71-ZQtPv6DohOw-JNL4XvJ2Vd9veG5BO-mvK6vUF2Epz7VyJdHVye4nrUo4JKM-OYlylBXgHbplCJhMY1QbQlP_2PiUW9DfyLs2oRF_z_xk4QT6NeSiXLQ2sTQx1d60DHvXdAck', 'Alice Munro captures the essence of life in her brilliant new collection of stories. Moments of change, chance encounters, the twist of fate that leads a person to a new way of thinking or being: the stories in Dear Life build to form a radiant, indelible portrait of just how dangerous and strange ordinary life can be.\r\n\r\n', 4, 336, 'https://books.google.fr/books?id=xueea93b7AwC&printsec=frontcover&dq=dear+life&hl=en&sa=X&ved=0ahUKEwi8-9LQgMfoAhVS4YUKHXjgCe0Q6AEIKDAA#v=onepage&q=dear%20life&f=false'),
(12, 'Les Miserables', 'Victor Hugo', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=k_LQBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71x5g08DliGT3c8FiWkqAt5YNYu9bPkmtiD4AUE3MhBv6ZQc0I8WRE3OjJJ-K_r6Q7hCJ47PP_t2t6v5GCgzfL42Kup1QLUBBZA9JwSLPjMJjI4xCsOuIL53D4j5g_n8fNApthC', 'Book lovers of all ages owe it to themselves to conquer this masterwork of nineteenth-century fiction from Victor Hugo, also author of The Hunchback of Notre-Dame. One hundred and fifty years after the original publication of Les Miserables, the heart-rending story of Jean Valjean, Fantine, Cosette and dozens of others of France\'s downtrodden and dispossessed continues to capture the imaginations of audiences around the world.', 5, 2121, 'https://books.google.fr/books?id=k_LQBAAAQBAJ&printsec=frontcover&dq=Les+Mis%C3%A9rables&hl=en&sa=X&ved=0ahUKEwjOu5yqhMjoAhWHyoUKHQz6CG8Q6AEIKDAA#v=onepage&q&f=false'),
(13, 'The Girl on the Train', 'Paula Hawkins, Rachel Wagstaff, Duncan Abel', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=p2SOBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71gsqlP4dieQQ1rl4c05zhdj0-zfVUMno93vFb7GF5RUO9aNQw4hZ-MqlivCY_c5yhgx9uIF00IPJ0hOzhGqHZsSQKgpuEX5YuqBTSQcCbRNsITpOzgPnHTHjXqrXmZDfMXqf5N', 'Rachel catches the same commuter train every morning. She knows it will wait at the same signal each time, overlooking a row of back gardens. She’s even started to feel like she knows the people who live in one of the houses. ‘Jess and Jason’, she calls them. Their life – as she sees it – is perfect. If only Rachel could be that happy.\r\n\r\nAnd then she sees something shocking. It’s only a minute until the train moves on, but it’s enough.\r\n\r\nNow everything’s changed. Now Rachel has a chance to become a part of the lives she’s only watched from afar.\r\n\r\nNow they’ll see; she’s much more than just the girl on the train...', 4, 416, 'https://books.google.fr/books?id=p2SOBAAAQBAJ&printsec=frontcover&dq=the+girl+on+the+train&hl=en&sa=X&ved=0ahUKEwjL9NH-_8boAhUK4BoKHd8LAcwQ6AEIMzAB#v=onepage&q=the%20girl%20on%20the%20train&f=false'),
(14, 'The Forty Rules of Love', 'Elif Shafak', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=Ykp0lB3K1LYC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73i_cAWm4elwvYkZ72kRsjjaE2nCoSz93gmk0kXqu9i_dj017GMLKSey5EADy5hsuSnKuG5XRwQAT6RhdqEqyPmKbZQXJ3GHwNbItMT7NUgTEZYy_3tSnwEzoxf7eb7szNpqJ1h', 'Ella Rubinstein has a husband, three teenage children, and a pleasant home. Everything that should make her confident and fulfilled. Yet there is an emptiness at the heart of Ella\'s life - an emptiness once filled by love.\r\nSo when Ella reads a manuscript about the thirteenth-century Sufi poet Rumi and Shams of Tabriz, and his forty rules of life and love, her world is turned upside down. She embarks on a journey to meet the mysterious author of this work.\r\nIt is a quest infused with Sufi mysticism and verse, taking Ella and us into an exotic world where faith and love are heartbreakingly explored. . .\r\n\'Enlightening, enthralling. An affecting paean to faith and love\' Metro\r\n\'Colourfully woven and beguilingly intelligent\' Daily Telegraph\r\n\'The past and present fit together beautifully in a passionate defence of passion itself\' The Times', 4.5, 368, 'https://books.google.fr/books?id=Ykp0lB3K1LYC&printsec=frontcover&dq=40+rules+of+love&hl=en&sa=X&ved=0ahUKEwiZvt_-gcfoAhWIxYUKHbDwD9YQ6AEIKDAA#v=onepage&q&f=false'),
(15, 'A Fraction Of The Whole', 'Steve Toltz', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=USXtUZTrdT0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70rGYocdr4RfHtv6A096iXvVoh44a0As9K2PKfTsS0HFEO0VIiUEdjPofonLeDVQrAlQgKaA8VpR9GEP80SAzFGXZxEzFkTDLvvLrhwyF1wNuEr8YOxMo7B_nAKgd8diQH0ttxW', 'From his prison cell, Jasper Dean tells the unlikely story of his scheming father Martin, his crazy Uncle Terry and how the three of them upset - mostly unintentionally - an entire continent. Incorporating death, parenting (good and bad kinds), one labyrinth, first love, a handbook for criminals, a scheme to make everyone rich and an explosive suggestion box, Steve Toltz\'s A Fraction of the Whole is a hilarious, heartbreaking story of families and how to survive them.\r\n\'A fat book but very light on its feet, skipping from anecdote, to rant, to reflection, like a stone skimming across a pond . . . it is brilliant\' Guardian\r\n\'Sparkling comic writing . . .It gives off the unmistakeable whiff of a book that might just contain the secret of life\' Independent\r\n\'With tinges of magical realism and buckets of misanthropic humour it\'s a clever and funny debut\' Observer\r\n\'If first novels were sandwiches, Steve Toltz\'s would be a juicy, swaggering doorstop of a sarnie, overflowing with eccentrically combined but delicious ingredients . . . Toltz is a superb phrase-maker with an acute eye for humanity\'s shortfalls\'Big Issue\r\nSteve Toltz was born in Sydney. After graduating from Newcastle University in 1994, he has lived in Sydney, Montreal, Vancouver, Barcelona and Paris, working primarily as a screenwriter and freelance writer, but also doing stints as both a private investigator and an English teacher. A Fraction of the Whole is his first book.', 4, 720, 'https://books.google.fr/books?id=USXtUZTrdT0C&printsec=frontcover&dq=a+friction+of+the+whole&hl=en&sa=X&ved=0ahUKEwiny73OgsfoAhUQyIUKHRQxAlEQ6AEIKDAA#v=onepage&q=a%20friction%20of%20the%20whole&f=false'),
(16, 'Me Before You', 'Jojo Moyes', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=rTYEyWrXLO0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72sG_iXdiAiJ6zlr3SBzCSAZE80Nsf0xFVKaLlr6UYn2WXe1mvvrtPtQNAeOYkPnVoXKnHnfblxx_CRCoW2Em5Fb4GnxI0wUJZYY-aSLgoBI8uPTU_2NpH49KacL4sdn8SbnvsR', 'They had nothing in common until love gave them everything to lose . . .\r\nLouisa Clark is an ordinary girl living an exceedingly ordinary life—steady boyfriend, close family—who has barely been farther afield than their tiny village. She takes a badly needed job working for ex–Master of the Universe Will Traynor, who is wheelchair bound after an accident. Will has always lived a huge life—big deals, extreme sports, worldwide travel—and now he’s pretty sure he cannot live the way he is.\r\nWill is acerbic, moody, bossy—but Lou refuses to treat him with kid gloves, and soon his happiness means more to her than she expected. When she learns that Will has shocking plans of his own, she sets out to show him that life is still worth living.\r\nA Love Story for this generation and perfect for fans of John Green’s The Fault in Our Stars, Me Before You brings to life two people who couldn’t have less in common—a heartbreakingly romantic novel that asks, What do you do when making the person you love happy also means breaking your own heart?', 4, 400, 'https://books.google.fr/books?id=rTYEyWrXLO0C&printsec=frontcover&dq=me+before+you&hl=en&sa=X&ved=0ahUKEwjn5NeHg8foAhVRXRoKHXcsDH0Q6AEIKDAA#v=onepage&q=me%20before%20you&f=false'),
(17, 'After You', 'Jojo Moyes', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=HW_MBgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72Ng8BSBQSURmaTTdQqITDzTux7wFi6zB9hEqaJbYyW69dX-KbSIERTEqYhPNJhVZyl7MGctTOlEzHixhb2GdJQYAbbbp0ubUEv3C8WvT8Ka6D3S_yaAKS_4z5E8zTrwtdCnJ06', 'Like how it is she\'s ended up working in an airport bar, spending every shift watching other people jet off to new places.\r\nOr why the flat she\'s owned for a year still doesn\'t feel like home.\r\nWhether her close-knit family can forgive her for what she did eighteen months ago.\r\nAnd will she ever get over the love of her life.\r\nWhat Lou does know for certain is that something has to change.\r\nThen, one night, it does.\r\nBut does the stranger on her doorstep hold the answers Lou is searching for - or just more questions?\r\nClose the door and life continues: simple, ordered, safe.\r\nOpen it and she risks everything.\r\nBut Lou once made a promise to live. And if she\'s going to keep it, she has to invite them in . . .', 4, 416, 'https://books.google.fr/books?id=HW_MBgAAQBAJ&printsec=frontcover&dq=me+after+you+jojo+moyes&hl=en&sa=X&ved=0ahUKEwi1yvzPg8foAhXhz4UKHW6QAa4Q6AEIKDAA#v=onepage&q=me%20after%20you%20jojo%20moyes&f=false'),
(18, 'Waiting for Godot', 'Samuel Beckett', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=FGhVMc7gN0EC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70XqdIQyubeiUOEhRZKrHHeQUJpm5CbbTVJhfAJW4J8KyIsq8uwRi_kEU5OwqqX5IPMVRa5pr0eOCkVelyhWboMqjnnmWPqNVUxAj6DmOOTomfaG0ms3hO7yCLW9OIbvxXWVute', 'From an inauspicious beginning at the tiny Left Bank Theatre de Babylone in 1953, followed by bewilderment among American and British audiences, Waiting for Godot has become of the most important and enigmatic plays of the past fifty years and a cornerstone of twentieth-century drama. As Clive Barnes wrote, “Time catches up with genius … Waiting for Godot is one of the masterpieces of the century.”\r\n\r\nThe story revolves around two seemingly homeless men waiting for someone—or something—named Godot. Vladimir and Estragon wait near a tree, inhabiting a drama spun of their own consciousness. The result is a comical wordplay of poetry, dreamscapes, and nonsense, which has been interpreted as mankind’s inexhaustible search for meaning. Beckett’s language pioneered an expressionistic minimalism that captured the existential post-World War II Europe. His play remains one of the most magical and beautiful allegories of our time.', 4.5, 128, 'https://books.google.fr/books?id=FGhVMc7gN0EC&printsec=frontcover&dq=waiting+for+godot&hl=en&sa=X&ved=0ahUKEwiQ5O2nhMfoAhVH1xoKHVvzDVoQ6AEIKzAA#v=onepage&q=waiting%20for%20godot&f=false'),
(19, 'The Alchemist', 'Paulo Coelho', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=FEL8DlqjYEkC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70KoPiswBrytCq2cv4DIKMEhtKqWx818uYXJ86IhilO9x9ZfoNQrajEOGqYhQDayuGzBlNeF0WUUcHnWB6tNklaMiD5EN306JX2P3DN2K1KaGZNL2xxLzIe6yqxI7H7Kk3kNY6H', '\"My heart is afraid that it will have to suffer,\" the boy told the alchemist one night as they looked up at the moonless sky.\" Tell your heart that the fear of suffering is worse than the suffering itself. And that no heart has ever suffered when it goes in search of its dreams.\"\r\nEvery few decades a book is published that changes the lives of its readers forever. The Alchemist is such a book. With over a million and a half copies sold around the world, The Alchemist has already established itself as a modern classic, universally admired. Paulo Coelho\'s charming fable, now available in English for the first time, will enchant and inspire an even wider audience of readers for generations to come.\r\nThe Alchemist is the magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found. From his home in Spain he journeys to the markets of Tangiers and across the Egyptian desert to a fateful encounter with the alchemist.\r\nThe story of the treasures Santiago finds along the way teaches us, as only a few stories have done, about the essential wisdom of listening to our hearts, learning to read the omens strewn along life\'s path, and, above all, following our dreams.', 4.5, 208, 'https://books.google.fr/books?id=FEL8DlqjYEkC&printsec=frontcover&dq=alchemist&hl=en&sa=X&ved=0ahUKEwjSz-zyhMfoAhVMzoUKHXjYCzQQ6AEIMTAB#v=onepage&q=alchemist&f=false'),
(20, 'Blindness', 'José Saramago', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=WME_6Yw0ZaIC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70PptSyMHnFtrLMz1G6eiZiquAjmoqLom2UvykcbQsSy4DVbHlUCS5z0WkPOMSnBjT0-wWflnleFSzIPRCPybJcTyDbdoDPQgDwC6qSDrUs1Q4lZJVkoOK7Pr_bPcHDdcuGjSl9', 'A driver waiting at the traffic lights goes blind. An ophthalmologist tries to diagnose his distinctive white blindness, but is affected before he can read the textbooks.\r\nIt becomes a contagion, spreading throughout the city. Trying to stem the epidemic, the authorities herd the afflicted into a mental asylum where the wards are terrorised by blind thugs. And when fire destroys the asylum, the inmates burst forth and the last links with a supposedly civilised society are snapped.', 4.5, 320, 'https://books.google.fr/books?id=WME_6Yw0ZaIC&printsec=frontcover&dq=Blindness&hl=en&sa=X&ved=0ahUKEwjN4dunhcfoAhWGyYUKHXJRBfwQ6AEIKDAA#v=onepage&q=Blindness&f=false'),
(21, 'When Nietzsche Wept', 'Irvin D. Yalom', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=9_WXDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72otk1Jj8srJltD-0VwbYpYDMe6k0ltmYjFRlMXwWZw34-4gq_dZZl0Iyth8YgHYC9mn4OjaFne30I8T9yZLbEWw0wRFwyuViGNeaT0FtCofFbwFTpzgn8agUENORKmE4MB7_b2', 'In nineteenth-century Vienna, a drama of love, fate, and will is played out amid the intellectual ferment that defined the era. Josef Breuer, one of the founding fathers of psychoanalysis, is at the height of his career. Friedrich Nietzsche, Europe\'s greatest philosopher, is on the brink of suicidal despair, unable to find a cure for the headaches and other ailments that plague him.\r\nWhen he agrees to treat Nietzsche with his experimental “talking cure,” Breuer never expects that he too will find solace in their sessions. Only through facing his own inner demons can the gifted healer begin to help his patient. In When ', 4, 320, 'https://books.google.fr/books?id=9_WXDwAAQBAJ&printsec=frontcover&dq=when+niche+cry&hl=en&sa=X&ved=0ahUKEwiF0PL4hcfoAhWvxYUKHddFDQYQ6AEIKDAA#v=onepage&q&f=false'),
(22, 'One Plus One', 'Jojo Moyes', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=vWY9e0LRJW4C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE733R9ZB0aTe-lsBVclocutiT7pfo8ZT6WwqEbDtN5JfVXhmrQZN32TIC1kWRDoMeeGeHqeOVFcPlklLsazyYmnnT0ZwrL5PhF4MHwhEHHj6OD2wb21hiu7qbuSqVOP8cO2t3Ett', 'One single mom. One chaotic family. One quirky stranger. One irresistible love story from the \"New York Times\" bestselling author of \"Me Before You\"\r\nAmerican audiences have fallen in love with Jojo Moyes. Ever since she debuted Stateside she has captivated readers and reviewers alike, and hit the \"New York Times\" bestseller list with the word-of-mouth sensation \"Me Before You.\" Now, with \"One Plus One,\" she\'s written another contemporary opposites-attract love story.\r\nSuppose your life sucks. A lot. Your husband has done a vanishing act, your teenage stepson is being bullied, and your math whiz daughter has a once-in-a-lifetime opportunity that you can\'t afford to pay for. That\'s Jess\'s life in a nutshell--until an unexpected knight in shining armor offers to rescue them. Only Jess\'s knight turns out to be Geeky Ed, the obnoxious tech millionaire whose vacation home she happens to clean. But Ed has big problems of his own, and driving the dysfunctional family to the Math Olympiad feels like his first unselfish act in ages . . . maybe ever.\r\n\"One Plus One\" is Jojo Moyes at her astounding best. You\'ll laugh, you\'ll weep, and when you flip the last page, you\'ll want to start all over again.', 3.5, 432, 'https://books.google.fr/books?id=vWY9e0LRJW4C&printsec=frontcover&dq=after+you+jojo+moyes&hl=en&sa=X&ved=0ahUKEwjmsoKep8foAhXZ8OAKHTBwDbMQ6AEIaTAI#v=onepage&q&f=false'),
(23, 'Sophie\'s World', 'Jostein Gaarder', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=J8nE3B5lD9AC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71DpJ-6oXPIJnpQOw_j4ROV0gPmrXxXdvkdIxily0n-jF954l7nQKwbSABFrzvCOPuZjeKeet_dvmP46KGafS_zbFFF-6jm9YDtoE5-k3M3mHPs4DaF35RchL9I52kbOgrVJfu8', 'When 14-year-old Sophie encounters a mysterious mentor who introduces her to philosophy, mysteries deepen in her own life. Why does she keep getting postcards addressed to another girl? Who is the other girl? And who, for that matter, is Sophie herself? To solve the riddle, she uses her new knowledge of philosophy, but the truth is far stranger than she could have imagined.\r\nA phenomenal worldwide bestseller, SOPHIE\'S WORLD sets out to draw teenagers into the world of Socrates, Descartes, Spinoza, Hegel and all the great philosophers. A brilliantly original and fascinating story with many twists and turns, it raises profound questions about the meaning of life and the origin of the universe.', 4.8, 448, 'https://books.google.fr/books?id=J8nE3B5lD9AC&printsec=frontcover&dq=sufi+world&hl=en&sa=X&ved=0ahUKEwih-cDYqsfoAhUNBWMBHfL0DXwQ6AEIMTAB#v=onepage&q&f=false'),
(25, 'Love in the Time of Cholera', 'Gabriel Garcia Marquez', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=kSGVAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71-10it5JHjxKWMRn8flg_x6U1ZOS9S68pU7uRu3_c6xgoalixmuLvRtBB6s8ltGjTSBctJaxDezh2uQct5reMJzsv9S2R3RwbkzOinwwmZjxnlMqIsxgX_FXBmIJ-EknxhUnlr', 'Fifty-one years, nine months and four days have passed since Fermina Daza rebuffed hopeless romantic Florentino Ariza\'s impassioned advances and married Dr Juvenal Urbino instead. During that half-century, Florentino has fallen into the arms of many delighted women, but has loved none but Fermina. Having sworn his eternal love to her, he lives for the day when he can court her again.\r\n\r\nWhen Fermina\'s husband is killed trying to retrieve his pet parrot from a mango tree, Florentino seizes his chance to declare his enduring love. But can young love find new life in the twilight of their lives?\r\n\r\n\'The most important writer of fiction in any language\' Bill Clinton\r\n\r\n\'An exquisite writer, wise, compassionate and extremely funny\' Sunday Telegraph\r\n\r\n\'An amazing celebration of the many kinds of love between men and women\' The Times', 4.5, 368, 'https://books.google.fr/books?id=kSGVAgAAQBAJ&printsec=frontcover&dq=love+in+the+time+of+Cholera&hl=en&sa=X&ved=0ahUKEwjr0fC_g8joAhXFzYUKHfcQDXIQ6AEIKDAA#v=onepage&q=love%20in%20the%20time%20of%20Cholera&f=false'),
(27, 'Great Expectations', 'Charles Dickens', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=KQAG1WS4AqgC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE707P0HUFj7SB_bji3Bl-xtVSJDQy7y95Dg5Kpws-_X8fWC2fee6Ug8PeD_-KH8owE1kwbXmbTWeNt6--9sLG7NZ-bLFYhJubjYww1R4QT240VkuQzCC05U7Zbgwb_rs0lZLsPWx', 'In this unflaggingly suspenseful story of aspirations and moral redemption, humble, orphaned Pip, a ward of his short-tempered older sister and her husband, Joe, is apprenticed to the dirty work of the forge but dares to dream of becoming a gentleman. And, indeed, it seems as though that dream is destined to come to pass — because one day, under sudden and enigmatic circumstances, he finds himself in possession of \"great expectations.\" In telling Pip\'s story, Dickens traces a boy\'s path from a hardscrabble rural life to the teeming streets of 19th-century London, unfolding a gripping tale of crime and guilt, revenge and reward, and love and loss. Its compelling characters include Magwitch, the fearful and fearsome convict; Estella, whose beauty is excelled only by her haughtiness; and the embittered Miss Havisham, an eccentric jilted bride.\r\nWritten in the last decade of Dickens\' life, Great Expectations was praised widely and universally admired. It was his last great novel, and many critics believe it to be his finest. Readers and critics alike praised it for its masterful plot, which rises above the melodrama of some of his earlier works, and for its three-dimensional, psychologically realistic characters — characters much deeper and more interesting than the one-note caricatures of earlier novels. \"In none of his other works,\" wrote the reviewer in the 1861 Atlantic, \"does he evince a shrewder insight into real life, and a cheaper perception and knowledge of what is called the world.\" To Swinburne, the novel was unparalleled in all of English fiction, with defects \"as nearly imperceptible as spots on the sun or shadows on a sunlit sea.\" Shaw found it Dickens\' \"most completely perfect book.\" Now this inexpensive edition invites modern readers to savor this timeless masterpiece, teeming with colorful characters, unexpected plot twists, and Dickens\' vivid rendering of the vast tapestry of mid-Victorian England.', 4.5, 400, 'https://books.google.fr/books?id=KQAG1WS4AqgC&printsec=frontcover&dq=Great+Expectations&hl=en&sa=X&ved=0ahUKEwiXjaCuucnoAhWFyqYKHY2ECAUQ6AEIMTAB#v=onepage&q=Great%20Expectations&f=false'),
(28, 'One Hundred Years of Solitude', 'Gabriel Garcia Marquez', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=RyGVAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70uOp1dy5H6kssW-G5c-2wv4Ou6qc5LVzSLZj7KI1mQrLIfM2D-YLDq79dNwGitc3gVYIMnyhxKSI_fIlZbs0qlqmD0jqGveKr-zwjve2leTuqDdTZKicimJvvxzn7rE9iBrY-X', 'One of the world\'s most famous novels, One Hundred Years of Solitude by Gabriel Garcia Marquez, winner of the Nobel Prize for Literature, blends the natural with the supernatural in one of the most magical reading experiences on earth.\r\n\r\n\'Many years later, as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon when his father took him to discover ice\'\r\n\r\nGabriel Garcia Marquez\'s great masterpiece is the story of seven generations of the Buendia family and of Macondo, the town they have built. Though little more than a settlement surrounded by mountains, Macondo has its wars and disasters, even its wonders and its miracles. A microcosm of Columbian life, its secrets lie hidden, encoded in a book, and only Aureliano Buendia can fathom its mysteries and reveal its shrouded destiny. Blending political reality with magic realism, fantasy and comic invention, One Hundred Years of Solitude is one of the most daringly original works of the twentieth century.\r\n\r\n\'Dazzling\' The New York Times', 4.8, 432, 'https://books.google.fr/books?id=RyGVAgAAQBAJ&printsec=frontcover&dq=One+Hundred+Years+of+Solitude&hl=en&sa=X&ved=0ahUKEwjnsteCusnoAhUUw8QBHUSIBTgQ6AEIWzAG#v=onepage&q=One%20Hundred%20Years%20of%20Solitude&f=false'),
(29, 'A Room of One\'s Own', 'Virginia Woolf, General Press', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=0Rm0DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73Z0hSH6s2eDERSITrQtQUL79Qa8sJ87xBIv1-Rlp68I8MgSiPEWIwsE1-qAaoAmu0UFlesHGbf467PBq-Px7CS7zJHbOCXCnL0EPuflViusQvBK7LdA8FEeKrZRQFjKtibp-3b', 'In A Room of One\'s Own, Virginia Woolf imagines that Shakespeare had a sister—a sister equal to Shakespeare in talent, and equal in genius, but whose legacy is radically different. This imaginary woman never writes a word and dies by her own hand, her genius unexpressed. If only she had found the means to create, argues Woolf, she would have reached the same heights as her immortal sibling. In this classic essay, she takes on the establishment, using her gift of language to dissect the world around her and give voice to those who are without. Her message is a simple one—women must have a fixed income and a room of their own in order to have the freedom to create.\r\n\r\nWoolf\'s blazing polemic on female creativity, the role of the writer, and the silent fate of Shakespeare\'s imaginary sister remains a powerful reminder of a woman\'s need for financial independence and intellectual freedom.', 4, 320, 'https://books.google.fr/books?id=0Rm0DwAAQBAJ&printsec=frontcover&dq=A+Room+of+One%27s+Own&hl=en&sa=X&ved=0ahUKEwjBt4n6usnoAhWM0KYKHTbjBTsQ6AEIKDAA#v=onepage&q=A%20Room%20of%20One\'s%20Own&f=false'),
(30, 'David Copperfield', 'Charles Dickens', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=bPhICgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71Ol7k-CKNq2v4GkPVUNaUoIEku4drFGp78qNGRfnkTgqeLH8Y1Ox_65EhLgvqMKGRlwIFVfZtNCl3KmZX60bJ5q2h154HfwoujNmzMQWy2UkGLXxVg1cH9SsMBSDpXPVGSfqTV', 'David Copperfield’s happy life suddenly changes when his mother marries again. Her new husband is cruel to him and sends him away to school. When David’s mother dies, he is sent to work in London. He hates his job so he runs away. He has no money for food or for travelling. But it is the beginning of his life of adventure.', 4, 112, 'https://books.google.fr/books?id=bPhICgAAQBAJ&printsec=frontcover&dq=David+Copperfield&hl=en&sa=X&ved=0ahUKEwiu0ITeu8noAhUJGpoKHY4uBVkQ6AEITDAF#v=onepage&q=David%20Copperfield&f=false'),
(31, 'Ansichten eines Clowns', 'Heinrich Böll', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=M85mAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72YMkg2NDnCXwTrWPPTZAh4gEX8owjDteg7OE3bKQ2wQ00HAHOSrd-srpoZ1abLuV1W4yXbncaEkvoRVaIn9u959HMt8vY2rsxoEfSBQSvizoz0baEOspp_ohzajimZcrG6RhvJ', 'Mit Hans Schnier, dem »Clown«, der in der Maske des Pantomimen die äußerste Wahrheit sagt, hat Heinrich Böll eine Reizfigur geschaffen. Selten hat ein Buch der Nachkriegszeit derart erregte Diskussionen ausgelöst wie die Ansichten eines Clowns, die die Moral und den Lebensstil der bürgerlich-katholischen Gesellschaft in ihrem Nerv trafen. Die Geschichte vom langsamen gesellschaftlichen Abstieg des Ich-Erzählers Hans Schnier ist zugleich eine Liebesgeschichte, die zeigt, dass die Liebe scheitert, wenn einer den Konventionen mehr verhaftet ist als der andere. Und dass durch die Liebe die Augen schärfer werden für alles, was außerhalb der Welt des Clowns und seiner Geliebten falsch und erbarmungswürdig ist. Dieser Blick, der die gesellschaftliche Bedrohung der Liebe enthüllt, hat eine fortdauernde Gültigkeit. Bölls meistdiskutierter Roman führt vor, was geschieht, wenn Liebe und gesellschaftliche Konventionen aufeinanderprallen. Ein Portrait der bürgerlich-katholischen Gesellschaft Anfang der Sechziger Jahre und Anlass für eine heftige Kontroverse in der literarischen Kritik sowie eine Debatte um die Rolle des Katholizismus in der Bundesrepublik. Informieren Sie sich auch über das größte editorische Unternehmen in der Geschichte des Verlags Kiepenheuer & Witsch: Heinrich Böll, Werke 1 - 27 Kölner Ausgabe\r\n', 4, 288, 'https://books.google.fr/books?id=M85mAgAAQBAJ&printsec=frontcover&dq=Ansichten+Eines+Clowns&hl=en&sa=X&ved=0ahUKEwiFkbbYvcnoAhVPC-wKHab4DOkQ6AEIKzAA#v=onepage&q=Ansichten%20Eines%20Clowns&f=false'),
(32, 'Wilful Disregard', 'Lena Andersson', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=h9waBwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71KymZgDhcUOYq7x3-sTspS4f8WFIquzzsJOQsKCXnzPcrVX1irMBZcCjpj0TqOUx7vsHuk40k8_1uDyftpe-obeBlUxWueyld5bz1gbQwDZb5ZGLZFaT33ok15xcTeXbvrrgX5', '\'Gripped me like an airport read . . . perfect.\' Lena Dunham\r\n\r\n\'Lena Andersson\'s Wilful Disregard is a story of the heart written with bracing intellectual rigor. It is a stunner, pure and simple.\' Alice Sebold, author of The Lovely Bones\r\n\r\nWinner of the August Prize 2013\r\n\r\nOn the day that Ester Nilsson, a poet and a sensible person in a sensible relationship, meets renowned artist Hugo Rask, her rational world begins to unravel. Leaving her boyfriend and her past behind, Ester embarks on what is sure to be the greatest love story of her life.\r\n\r\nIt\'s a shame no one else agrees.', 3.8, 208, 'https://books.google.fr/books?id=h9waBwAAQBAJ&printsec=frontcover&dq=Wilful+Disregard&hl=en&sa=X&ved=0ahUKEwjr5tuuvsnoAhVPzMQBHd5wCU4Q6AEIKDAA#v=onepage&q=Wilful%20Disregard&f=false'),
(33, 'The Master and Margarita', 'Mikhail Bulgakov, Edward Kemp', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=-zI2DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE712nL1-1lKuykrvrpgg-JwiPUINLdP31fAtM_Nx-S5wIXDxxt4UFVzb0hCwWXhnGT_mXODmNsvwuuvcTyNOb1QaEXg5lU2Uj1_jltDBT1LldIJByIizgtStxeu8y8wSPi8VCLar', 'A mysterious stranger appears in a Moscow park. Soon he and his retinue have astonished the locals with the magic show to end all magic shows. But why are they really here, and what has it got todo with the beautiful Margarita, or her lover, the Master, a silenced writer? A carnival for the senses and a diabolical extravaganza, this most exuberant of Russian novels was staged in this adaptation at Chichester Festival Theatre.', 4, 96, 'https://books.google.fr/books?id=-zI2DwAAQBAJ&printsec=frontcover&dq=The+Master+and+Margarita&hl=en&sa=X&ved=0ahUKEwi6x6yRv8noAhVuzqYKHdQLC3QQ6AEIMTAB#v=onepage&q=The%20Master%20and%20Margarita&f=false'),
(34, 'Old Man and the Sea', 'Ernest Hemingway', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=P-BSAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71tjNTPL68zHIPoZROZ536EWvXL2OiINGBXNtmf7Te--J3bfMgJCjCtTGgcH9qC5k1oHcs6mJ_OE60qv7WqYIyre-pdYuI1Xp-DxkSaZsLrelK1VKljH72wOXw2M4O2BimijLmR', 'The last novel Ernest Hemingway saw published, The Old Man and the Sea has proved itself to be one of the enduring works of American fiction. It is the story of an old Cuban fisherman and his supreme ordeal: a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. Using the simple, powerful language of a fable, Hemingway takes the timeless themes of courage in the face of defeat and personal triumph won from loss and transforms them into a magnificent twentieth-century classic.', 4.5, 100, 'https://books.google.fr/books?id=P-BSAgAAQBAJ&printsec=frontcover&dq=The+Old+Man+and+the+Sea&hl=en&sa=X&ved=0ahUKEwieycXKv8noAhWD6qQKHc9fBXkQ6AEIMTAB#v=onepage&q=The%20Old%20Man%20and%20the%20Sea&f=false'),
(35, 'Zorba the Greek', 'Nikos Kazantzakis', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=ZXPbBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71k-5RQG1PTU_dLLyfhTQqmP2dd80__p9M-pe38LqKdl1jQCBn9iTV5pFjAqqzPtwhjDnssIrWONAx8EPGORUWIha7gJx709G7Su0ESTTrq-yZ0LGvQtT-EUOz75NNcWsiB3LLn', 'A stunning new translation of the classic book—and basis for the beloved Oscar-winning film—brings the clarity and beauty of Kazantzakis’s language and story alive.\r\n\r\nFirst published in 1946, Zorba the Greek, is, on one hand, the story of a Greek working man named Zorba, a passionate lover of life, the unnamed narrator who he accompanies to Crete to work in a lignite mine, and the men and women of the town where they settle. On the other hand it is the story of God and man, The Devil and the Saints; the struggle of men to find their souls and purpose in life and it is about love, courage and faith.\r\n\r\nZorba has been acclaimed as one of the truly memorable creations of literature—a character created on a huge scale in the tradition of Falstaff and Sancho Panza. His years have not dimmed the gusto and amazement with which he responds to all life offers him, whether he is working in the mine, confronting mad monks in a mountain monastery, embellishing the tales of his life or making love to avoid sin. Zorba’s life is rich with all the joys and sorrows that living brings and his example awakens in the narrator an understanding of the true meaning of humanity. This is one of the greatest life-affirming novels of our time.\r\n\r\nPart of the modern literary canon, Zorba the Greek, has achieved widespread international acclaim and recognition. This new edition translated, directly from Kazantzakis’s Greek original, is a more faithful rendition of his original language, ideas, and story, and presents Zorba as the author meant him to be.', 3.5, 349, 'https://books.google.fr/books?id=ZXPbBQAAQBAJ&printsec=frontcover&dq=Zorba+the+Greek&hl=en&sa=X&ved=0ahUKEwid9tX4v8noAhVO3KQKHWysASIQ6AEIOTAC#v=onepage&q=Zorba%20the%20Greek&f=false'),
(36, 'The Catcher in the Rye and Philosophy', 'Keith Dromm, Heather Salter', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=PuLrwrABKFoC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72XsczA-_aC7p69xuNXD4eOIpcufvPZ4nxKyEkhbl2w9TwC1rTTEdhZwv_4OKUz-m0wo-97XeQW0F47vHNALJCKsuOT2VHi-6TViSO82CZBHTeVdaRoWSBweNBxZ6kqZGjcixEs', 'Few novels have had more influence on individuals and literary culture than J.D. Salinger\'s The Catcher in the Rye. Published in 1951 and intended by Salinger for adults (early drafts were published in the New Yorker and Colliers), the novel quickly became championed by youth who identified with the awkwardness and alienation of the novel\'s protagonist, Holden Caulfield. Since then the book and its reclusive author have been fixtures of both popular and literary culture. Catcher is perhaps the only modern novel that is revered equally by the countless Americans whom Holden Caulfield helped through high school and puberty and literary critics (such as the New Yorker\'s Adam Gopnik who insisted as recently as 2010 that Catcher is a \"perfect\" twentieth-century novel).\r\n\r\nOne premise of The Catcher in the Rye and Philosophy is that the ease and sincerity with which readers identify with Holden Caulfield rests on Salinger\'s attention to the nuances and qualities of experience in the modern world. Coupled with Salinger\'s deft subjective, first-person style, Holden comes to seem more real than any fictional character should. This and other paradoxes raised by the novel are treated by authors who find answers in philosophy, particularly in twentieth-century phenomenology and existentialism--areas of philosophy that share Salinger\'s attention to lived, as opposed to theorized, experience. Holden\'s preoccupation with ?phonies,” along with his constant striving to interpret and judge the motives and beliefs of those around him, also taps into contemporary interest in philosophical theories of justice and Harry Frankfurt\'s recently celebrated analysis of \"bullshit.\"\r\n\r\nPer Salinger\'s request, Catcher has never been made into a movie. One measure of the devotion and fanatical interest Catcher continues to inspire, however, is speculation in blogs and magazines about whether movie rights may become available in the wake of Salinger\'s death in 2010. These articles remain purely hypothetical, but the questions they inspire--Who would direct? And, especially, Who would star as Holden Caulfield?--are as vivid and real as Holden himself.', 4.3, 215, 'https://books.google.fr/books?id=PuLrwrABKFoC&printsec=frontcover&dq=The+Catcher+in+the+Rye&hl=en&sa=X&ved=0ahUKEwj266C4wMnoAhUs06YKHXqcAzwQ6AEINjAC#v=onepage&q=The%20Catcher%20in%20the%20Rye&f=false');
INSERT INTO `Book` (`id`, `name`, `author`, `translator`, `publisher`, `category`, `photo`, `descr`, `rate`, `page_nr`, `link`) VALUES
(37, 'Nineteen Eighty-Four (1984)', 'George Orwell, Matthew Dunster', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=vaDa9gd1IqEC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70iN4IN9xDj53Jr99BwLyeaSxYCuyc27wK2RXq4BO-4DOulc36I0gdEyZ_0ntbyof2_Kjrh7cltUMp3F7KfVCXLQPBNuaCDkqKej8FaqxDrRBNqYC28EeS6bYGc3vFpwZyR-vAW', 'War is Peace. Freedom is Slavery. Ignorance is Strength.\r\n\r\nWinston Smith rewrites history for the Ministry of Truth, but when he’s handed a note that says simply ‘I love you’ by a woman he hardly knows, he decides to risk everything in a search for the real truth. In a world where cheap entertainment keeps the proles ignorant but content, where a war without end is always fought and the government is always watching, can Winston possibly hold onto what he feels inside? Or will he renounce everything, accept the Party’s reality and learn to love Big Brother?\r\n\r\n‘Dunster – both in his faithful take on the story and in his sometimes extreme but always enthralling adaptation – gets close to the heart of Orwell’s warning, pointing up but not overemphasising its current political resonances.... Newspeak, Doublethink, Room 101 and Thought Police take on a chilling reality in this compelling production.’ – The Independent', 4.5, 120, 'https://books.google.fr/books?id=vaDa9gd1IqEC&printsec=frontcover&dq=1984&hl=en&sa=X&ved=0ahUKEwjh7cGmwcnoAhVCwsQBHfdVBS0Q6AEITDAE#v=onepage&q=1984&f=false'),
(38, 'Daddy Long-Legs', 'Jean Webster', NULL, NULL, NULL, 'https://books.google.fr/books/content?id=HeWECgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE70HLuvG54PPL-MHAPNa-NBdhH5E5NX_2DyO--orX5XvaqatyAjsmtzVPKo0F0oPwbl_CD_z14AtycoZqCFuhiOLiISukJDzI9W-cxXdZsKauAYV0AdugY63uzLLGkiccAT0uftH', 'A trustee of the John Grier orphanage has offered to send Judy Abbott to college. The only requirements are that she must write to him every month and that she can never know who he is. Judy\'s life at college is a whirlwind of friends, classes, parties and a growing friendship with the handsome Jervis Pendleton. With so much happening in her life, Judy can scarcely stop writing to \'Daddy-Long-Legs\', or wondering who her mysterious benefactor is...', 4, 208, 'https://books.google.fr/books?id=HeWECgAAQBAJ&printsec=frontcover&dq=daddy+long+leg&hl=en&sa=X&ved=0ahUKEwiYz4mswsnoAhUowqYKHZYVARcQ6AEIKDAA#v=onepage&q=daddy%20long%20leg&f=false');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Book`
--
ALTER TABLE `Book`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id_book` (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Book`
--
ALTER TABLE `Book`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
